package com.jay.android.dispatcher.compiler.utils

import com.jay.android.dispatcher.common.CommonConst.PROJECT


/**
 * APT 常量
 *
 * @author jaydroid
 * @version 1.0
 * @date 7/8/21
 */
object AptConst {

    // Generate

    const val WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY JDISPATCHER \n"
    const val METHOD_LOAD_INTO = "loadInto"
    const val PARAM_LOADINTO = "atlas"

    // Log
    const val TAG = "$PROJECT::Compiler > > "

    // process
    const val COMMON_PACKAGE = "com.jay.android.dispatcher"
    const val IDISPATCH_GROUP = "$COMMON_PACKAGE.common.IDispatchGroup"
    const val DISPATCH_ITEM_CANONICAL_NAME: String = "$COMMON_PACKAGE.common.DispatchItem"

}